version: "3"

services:
  back:
    build: 
      context: ./backend/kanban-backend
      dockerfile: Dockerfile
    image: kanban-server:1.0
    networks:
        - default
    ports:
        - "8081:8080"
    depends_on:
        - database
  database:
    image: postgres
    restart: always
    hostname: rosstrello-database
    env_file:
      - db/vars_db.env
    ports:
      - "5431:5432"
    networks:
      - "default"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
  
